/**
 * molique-jit - `make:carousel` (Scaffolding)
 *
 * Markup verified against css/scss/components/_carousel.scss (.carousel >
 * .carousel-track > .carousel-slide, native scroll-snap, zero JS for the
 * scrolling itself) and src/examples-carousel.html.
 *
 * IMPORTANT: `.carousel-dots`/`.carousel-dot` (pagination dots) are
 * generated by js/modules/molique-carousel.js ITSELF, when there is more
 * than 1 slide and they aren't already in the markup - the generator does
 * NOT add them by hand, matching what the real example shows (the dots
 * are NOT in the page's source code, even though they're visible in the
 * rendered preview).
 *
 * Two STRUCTURALLY different variants (basic: cards with text vs
 * bg-sync: per-slide background via data-bg + overlay), hence separate
 * stubs.
 *
 * A11y: in the real example, bg-sync does NOT have an aria-label on the
 * navigation arrows (unlike the basic variant, which has "Previous"/
 * "Next" - apparently an oversight in the same docs file), the generator
 * adds them consistently in BOTH variants. The inline `style="z-index:
 * 4"` on the bg-sync arrows in the example is redundant -
 * `.carousel-bg-sync .carousel-nav` in SCSS already sets that z-index, so
 * the generator omits it.
 */

import type { Command } from 'commander';
import { select, input } from '@inquirer/prompts';
import { renderStub, renderList } from '../stubs.js';
import { outputResult } from './output.js';
import { promptCount } from './prompts.js';
import { loadAnswers } from './answers.js';

/* ---------- Basic ---------- */

type SlideColor = 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'dark';

// The same light/dark text classification against a colored background
// used across the repo (_colors.scss hover loop, FUNNEL_PALETTE in
// make-chart.ts): primary/secondary/dark -> light text, success/danger/
// warning/info -> dark (default) text - exactly the asymmetry visible in
// the real example (bg-primary/bg-dark get text-white, bg-success does
// not).
const LIGHT_TEXT_COLORS = new Set<SlideColor>(['primary', 'secondary', 'dark']);

const COLOR_CHOICES = [
  { name: 'Primary', value: 'primary' },
  { name: 'Dark', value: 'dark' },
  { name: 'Success', value: 'success' },
  { name: 'Secondary', value: 'secondary' },
  { name: 'Danger', value: 'danger' },
  { name: 'Warning', value: 'warning' },
  { name: 'Info', value: 'info' },
] as const;

export interface CarouselBasicAnswers {
  maxWidth: string;
  slides: Array<{ title: string; text: string; color: SlideColor }>;
}

async function collectCarouselBasicAnswers(countFlag?: string): Promise<CarouselBasicAnswers> {
  const maxWidth = await input({ message: 'Maximum carousel width:', default: '600px' });
  const count = await promptCount({ message: 'How many slides?', default: '3', min: 1, max: 8, flagValue: countFlag });

  const slides: CarouselBasicAnswers['slides'] = [];
  for (let i = 1; i <= count; i++) {
    const title = await input({ message: `  Slide ${i} title:`, default: `Slide ${i}` });
    const text = await input({ message: `  Slide ${i} text:`, default: 'Swipe or use the arrows' });
    const color = await select<SlideColor>({
      message: `  Slide ${i} background color?`,
      choices: COLOR_CHOICES,
      default: (['primary', 'dark', 'success'][(i - 1) % 3] as SlideColor),
    });
    slides.push({ title, text, color });
  }

  return { maxWidth, slides };
}

export function renderCarouselBasic(answers: CarouselBasicAnswers): string {
  const SLIDES = renderList(
    '_carousel-slide-basic.stub.html',
    answers.slides.map((s) => ({
      TITLE: s.title,
      TEXT: s.text,
      COLOR: s.color,
      TEXT_CLASS: LIGHT_TEXT_COLORS.has(s.color) ? ' text-white' : '',
    }))
  );
  return renderStub('carousel-basic.stub.html', { MAX_WIDTH: answers.maxWidth, SLIDES });
}

/* ---------- Hero (Background Sync) ---------- */

export interface CarouselBgSyncAnswers {
  height: string;
  slides: Array<{ bg: string; heading: string }>;
}

async function collectCarouselBgSyncAnswers(countFlag?: string): Promise<CarouselBgSyncAnswers> {
  const height = await input({ message: 'Carousel height:', default: '400px' });
  const count = await promptCount({ message: 'How many slides?', default: '2', min: 1, max: 8, flagValue: countFlag });

  const slides: CarouselBgSyncAnswers['slides'] = [];
  for (let i = 1; i <= count; i++) {
    const bg = await input({ message: `  Slide ${i} background photo URL:`, default: `img/slide-${i}.jpg` });
    const heading = await input({ message: `  Slide ${i} heading:`, default: `Heading ${i}` });
    slides.push({ bg, heading });
  }

  return { height, slides };
}

export function renderCarouselBgSync(answers: CarouselBgSyncAnswers): string {
  const SLIDES = renderList(
    '_carousel-slide-bg-sync.stub.html',
    answers.slides.map((s) => ({ BG: s.bg, HEADING: s.heading }))
  );
  return renderStub('carousel-bg-sync.stub.html', { HEIGHT: answers.height, SLIDES });
}

/* ---------- Dispatch ---------- */

export type CarouselAnswers =
  | ({ type: 'basic' } & CarouselBasicAnswers)
  | ({ type: 'bg-sync' } & CarouselBgSyncAnswers);

function renderCarousel(answers: CarouselAnswers): string {
  return answers.type === 'basic' ? renderCarouselBasic(answers) : renderCarouselBgSync(answers);
}

async function collectCarouselAnswers(countFlag?: string): Promise<CarouselAnswers> {
  const type = await select<CarouselAnswers['type']>({
    message: 'Which carousel variant?',
    choices: [
      { name: 'Basic (cards with text)', value: 'basic' },
      { name: 'Hero (background changes with the slide)', value: 'bg-sync' },
    ],
  });

  if (type === 'basic') return { type: 'basic', ...(await collectCarouselBasicAnswers(countFlag)) };
  return { type: 'bg-sync', ...(await collectCarouselBgSyncAnswers(countFlag)) };
}

/* ---------- Command registration ---------- */

export function registerMakeCarouselCommand(program: Command): void {
  program
    .command('make:carousel')
    .description('Interactive carousel generator (Basic / Hero Background Sync, native scroll-snap) (aliases: zrob:karuzele, mache:karussell)')
    .option('-n, --count <number>', 'Number of slides - skips this one question')
    .option('--answers <json>', 'Answers as JSON (CarouselAnswers shape, with a "type" field) - skips ALL questions')
    .option('--answers-file <path>', 'Path to a JSON file with answers - skips ALL questions')
    .option('-o, --out <path>', 'Save the result to a file (only works together with --answers/--answers-file)')
    .action(async (opts: { count?: string; answers?: string; answersFile?: string; out?: string }) => {
      const provided = loadAnswers<CarouselAnswers>(opts);
      const answers = provided ?? (await collectCarouselAnswers(opts.count));
      const html = renderCarousel(answers);
      await outputResult(html, `components/carousel-${answers.type}.html`, provided ? { out: opts.out } : undefined);
    });
}
