/**
 * molique-jit - `make:carousel` tests
 *
 * Run with:  node tools/run-scaffolding-tests.mjs
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const { renderCarouselBasic, renderCarouselBgSync } = await import(
  pathToFileURL(path.join(root, 'tools', 'jit', 'package', 'dist', 'cli', 'make-carousel.js')).href
);

test('make:carousel - Basic: arrows have aria-label, no dots in the markup', () => {
  const html = renderCarouselBasic({
    maxWidth: '600px',
    slides: [{ title: 'Slide 1', text: 'Text', color: 'primary' }],
  });
  assert.match(html, /aria-label="Previous"/);
  assert.match(html, /aria-label="Next"/);
  assert.doesNotMatch(html, /carousel-dot/); // dots are generated by JS, not the generator
});

test('make:carousel - primary/dark/secondary get text-white, success/danger/warning/info do not', () => {
  const light = renderCarouselBasic({ maxWidth: '600px', slides: [{ title: 'A', text: 'A', color: 'primary' }] });
  const dark = renderCarouselBasic({ maxWidth: '600px', slides: [{ title: 'A', text: 'A', color: 'success' }] });
  assert.match(light, /bg-primary text-white/);
  assert.match(dark, /bg-success rounded-2/);
  assert.doesNotMatch(dark, /bg-success text-white/);
});

test('make:carousel - BG-Sync: data-bg on the slide, overlay present, no inline z-index (already in CSS)', () => {
  const html = renderCarouselBgSync({
    height: '400px',
    slides: [{ bg: 'img/a.jpg', heading: 'Architecture' }],
  });
  assert.match(html, /class="carousel carousel-bg-sync w-100" style="height: 400px"/);
  assert.match(html, /class="carousel-bg-overlay">/);
  assert.match(html, /data-bg="img\/a\.jpg"/);
  assert.doesNotMatch(html, /z-index/);
});

test('make:carousel - BG-Sync: arrows also have aria-label (fix relative to the real example)', () => {
  const html = renderCarouselBgSync({ height: '400px', slides: [{ bg: 'a.jpg', heading: 'A' }] });
  assert.match(html, /aria-label="Previous"/);
  assert.match(html, /aria-label="Next"/);
});
